=== Daniumy/arso22-proyecto-individual/MaestreYepes-Daniel-ciudades-rest/xml/ciudad.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:cs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.um.es/ciudad"
	xmlns="http://www.um.es/ciudad" elementFormDefault="qualified">

	<xs:element name="ciudad">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="id" type="xs:int" />
				<xs:element name="nombre" type="xs:string" />
				<xs:element name="codigoPostal" type="typeCodigoPostal" />
				<xs:element name="sitios-de-interes"
					type="typeSitiosInteres" />
				<xs:element name="parking-movilidad-reducida"
					type="typeParkingsMR" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="typeSitiosInteres">
		<xs:sequence>
			<xs:element name="sitioInteres" type="typeSitioInteres"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="typeSitioInteres">
		<xs:sequence>
			<cs:element name="id" type="xs:string" minOccurs="0" />
			<xs:element name="nombre" type="xs:string" />
			<xs:element name="descripcion" type="xs:string" />
			<xs:element name="foto" type="xs:string" minOccurs="0" />
			<xs:element name="comentario" type="xs:string"
				minOccurs="0" />
			<xs:element name="rank" type="xs:integer" />
			<xs:element name="direccion" type="typeDireccion" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="typeDireccion">
		<xs:sequence>
			<xs:element name="calle" type="xs:string" />
			<xs:element name="numero" type="xs:integer" />
			<xs:element name="localidad" type="xs:string" />
			<xs:element name="codigoPostal" type="typeCodigoPostal" />
			<xs:element name="lat" type="xs:double" />
			<xs:element name="lng" type="xs:double" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="typeParkingsMR">
		<xs:sequence>
			<xs:element name="parking" type="typeParking"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="typeParking">
		<xs:sequence>
			<xs:element name="direccion" type="xs:string" />
			<xs:element name="foto" type="xs:string" minOccurs="0" />
			<xs:element name="longitud" type="xs:double" />
			<xs:element name="latitud" type="xs:double" />
			<xs:element name="numValoraciones" type="xs:int"
				minOccurs="0" />
			<xs:element name="calificacionMedia" type="xs:double"
				minOccurs="0" />
			<xs:element name="url" type="xs:string" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="typeCodigoPostal">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]*" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== Daniumy/arso22-proyecto-individual/MaestreYepes-Daniel-ciudades-rest/xml/ciudad.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ciudad xmlns="http://www.um.es/ciudad" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.um.es/ciudad ciudad.xsd">
    <id>1</id>
    <nombre>Lorca</nombre>
    <codigoPostal>30800</codigoPostal>
    <sitios-de-interes>
        <sitioInteres>
            <id>Palacio_de_los_Condes_de_San_Juli%C3%A1n</id>
            <nombre>Palacio de los Condes de San Julián</nombre>
            <descripcion>El palacio de los Condes de San Julián es una casa solariega situada en la ciudad de Lorca (Región
            de Murcia, España) cuyos orígenes se remontan al siglo XVII, aunque su apariencia externa está alterada por
            modificaciones realizadas en el siglo XVIII otorgándole aspecto de fortaleza, y neomudéjares (...)
        </descripcion>
            <rank>19</rank>
            <direccion>
                <calle>Avenida Juan Carlos I</calle>
                <numero>2</numero>
                <localidad>San Mateo</localidad>
                <codigoPostal>30800</codigoPostal>
                <lat>37.6713</lat>
                <lng>-1.6988</lng>
            </direccion>
        </sitioInteres>
        <sitioInteres>
            <id>Estaci%C3%B3n_de_Lorca-Sutullena</id>
            <nombre>Estación de Lorca-Sutullena</nombre>
            <descripcion>Lorca-Sutullena es, junto a Lorca-San Diego una de las dos estaciones de ferrocarril de la ciudad
            española de Lorca, en la Región de Murcia. Está situada junto a la plaza de Carruajes, próxima al centro
            urbano y junto a la plaza de Toros de Sutullena (...)
        </descripcion>
            <rank>91</rank>
            <direccion>
                <calle>Avenida Periodista Lopez Barne</calle>
                <numero>10</numero>
                <localidad>San Mateo</localidad>
                <codigoPostal>30800</codigoPostal>
                <lat>37.6719</lat>
                <lng>-1.6961</lng>
            </direccion>
        </sitioInteres>
        <sitioInteres>
            <id>Tiata</id>
            <nombre>Tiata</nombre>
            <descripcion>Tiata es una pedanía del municipio español de Lorca, en la Región de Murcia. Es la pedanía de menor
            tamaño del municipio y se encuentra colindante a la capital de éste. Cuenta con 596 habitantes. En su
            término se sitúa el santuario de la Virgen de las Huertas, cuya construcción se remonta al siglo XVIII.​
        </descripcion>
            <rank>21</rank>
            <direccion>
                <calle>Calle Torrecilla</calle>
                <numero>8</numero>
                <localidad>San Jose</localidad>
                <codigoPostal>30800</codigoPostal>
                <lat>37.6665</lat>
                <lng>-1.7058</lng>
            </direccion>
        </sitioInteres>
        <sitioInteres>
            <id>Colegiata_de_San_Patricio</id>
            <nombre>Colegiata de San Patricio</nombre>
            <descripcion>La antigua colegiata de San Patricio de Lorca (aunque comúnmente sigue siendo llamada colegiata de
            San Patricio), es un edificio de estilo renacentista declarado Monumento Histórico-Artístico Nacional por
            decreto del 27 de enero de 1941.​ La Colegiata es la piedra angular del conjunto monumental de la Plaza de
            España, junto al Ayuntamiento, el Palacio del Corregidor y las Salas Capitulares. Esta Colegiata es la única
            en España que se encuentra bajo la advocación de San Patricio. La dedicación al santo irlandés, tiene su
            origen en la batalla de Los Alporchones, librada el 17 de marzo de 1452 (día de San Patricio), y que
            enfrentó a los habitantes de la ciudad y de otras partes del antiguo reino de Murcia con huestes musulmanas
            procedentes de Granada que habían asolado la comarca de Cartagena. Las obras comenzaron, por bula del papa
            Clemente VII, en 1533 sobre la vieja iglesia de San Jorge. La construcción, no exenta de problemas, se
            dilató hasta 1780 siguiendo el proyecto de Jerónimo Quijano, maestro de las Obras del Obispado de Cartagena.
            Concebida con aires catedralicios, su interior se articula en tres naves, doce capillas laterales en los
            contrafuertes, coro y trascoro, girola con capillas radiales y torre-campanario en la cabecera. También es
            de destacar el elevado crucero.
        </descripcion>
            <rank>91</rank>
            <direccion>
                <calle>Calle Abad De Los Arcos</calle>
                <numero>2</numero>
                <localidad>Parroquias Altas</localidad>
                <codigoPostal>30800</codigoPostal>
                <lat>37.6775</lat>
                <lng>-1.6994</lng>
            </direccion>
        </sitioInteres>
        <sitioInteres>
            <id>Iglesia_de_Santiago_%28Lorca%29</id>
            <nombre>Iglesia de Santiago (Lorca)</nombre>
            <descripcion>La iglesia de Santiago de Lorca, es un templo barroco que tiene como origen previo a la iglesia una
            ermita del siglo XV en honor al mismo santo. Esa ermita fue ubicada donde, según cuenta la tradición, había
            predicado el apóstol (...)
        </descripcion>
            <rank>67</rank>
            <direccion>
                <calle>Calle Villaescusa</calle>
                <numero>1</numero>
                <localidad>Santiago</localidad>
                <codigoPostal>30800</codigoPostal>
                <lat>37.6772</lat>
                <lng>-1.6981</lng>
            </direccion>
        </sitioInteres>
        <sitioInteres>
            <id>Castillo_de_Lorca</id>
            <nombre>Castillo de Lorca</nombre>
            <descripcion>El Castillo de Lorca (Murcia, España) es una fortaleza de origen medieval construida entre los
            siglos IX y XV. Comprende una serie de estructuras defensivas que, durante la Edad Media, convirtieron a la
            ciudad y a su fortaleza en un punto inexpugnable del sureste peninsular. El castillo de Lorca fue un bastión
            clave en las contiendas entre cristianos y musulmanes en la frontera de Granada. Se encuentra catalogado
            como Bien de Interés Cultural​ y dentro de la delimitación del conjunto histórico-artístico de Lorca.​​ Por
            su extensión, 640 metros de largo por unos 120 metros en su punto más ancho, es uno de los castillos más
            grandes de España.
        </descripcion>
            <foto>http://commons.wikimedia.org/wiki/Special:FilePath/Castillo_de_Lorca1.jpg?width=300</foto>
            <rank>92</rank>
            <direccion>
                <calle></calle>
                <numero>0</numero>
                <localidad></localidad>
                <codigoPostal></codigoPostal>
                <lat>37.6775</lat>
                <lng>-1.7058</lng>
            </direccion>
        </sitioInteres>
        <sitioInteres>
            <id>Museo_Arqueol%C3%B3gico_Municipal_de_Lorca</id>
            <nombre>Museo Arqueológico Municipal de Lorca</nombre>
            <descripcion>El museo Arqueológico Municipal de Lorca (Murcia), España, fue fundado en marzo de 1992 y se
            encuentra en la plaza de Juan Moreno. El Ayuntamiento de Lorca es el encargado de la titularidad y gestión
            del museo. El museo nació con el fin de un mejor desarrollo cultural de Lorca y la comarca. (...)
        </descripcion>
            <rank>72</rank>
            <direccion>
                <calle>Plaza Don Juan Moreno</calle>
                <numero>12</numero>
                <localidad>Santiago</localidad>
                <codigoPostal>30800</codigoPostal>
                <lat>37.6785</lat>
                <lng>-1.6966</lng>
            </direccion>
        </sitioInteres>
        <sitioInteres>
            <id>Lorca</id>
            <nombre>Lorca</nombre>
            <descripcion>Lorca es una ciudad y municipio español perteneciente a la Región de Murcia, situada en la comarca
            del Alto Guadalentín, en el sureste de la península ibérica. Es la tercera población en importancia de la
            Región de Murcia tras Murcia y Cartagena, con 94 404 habitantes (INE 2019); de ellos, 60 914 habitantes
            corresponden al casco urbano​ y el resto a sus numerosas pedanías, distribuidas a lo largo y ancho de los 1
            675 km² de término municipal,​ el segundo más extenso de España tras el de Cáceres. Lorca es conocida por su
            castillo, su arquitectura barroca y sus procesiones de Semana Santa, declaradas fiesta de interés turístico
            internacional. Gracias a su denso patrimonio heráldico es también llamada «la ciudad de los cien escudos»,
            nombre que le otorgó el antiguo alcalde José Antonio Gallego,​​ mientras que de su nombre original
            (Eliocroca) toma el título de ciudad del sol.​​​Su casco antiguo y el recinto del castillo,​ fueron
            declarados conjunto histórico-artístico el 5 de marzo del 1964,​ siendo el primero de la Región de Murcia
            con esta distinción. ​​
        </descripcion>
            <rank>100</rank>
            <direccion>
                <calle>Alameda Poeta Para Vico</calle>
                <numero>3</numero>
                <localidad>Santiago</localidad>
                <codigoPostal>30800</codigoPostal>
                <lat>37.6798</lat>
                <lng>-1.6944</lng>
            </direccion>
        </sitioInteres>
        <sitioInteres>
            <id>Sutullena</id>
            <nombre>Sutullena</nombre>
            <descripcion>Sutullena es una localidad y pedanía española perteneciente al municipio de Lorca, en la parte
            central de la comarca del Alto Guadalentín, Región de Murcia. Cerca de esta localidad se encuentran los
            núcleos de Tiata, Campillo y Torrecilla. Es la pedanía más poblada del municipio lorquino.
        </descripcion>
            <rank>12</rank>
